# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - main: ./cmd/please
    binary: please
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore certain OS/arch combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: please
    repository:
      owner: iishyfishyy
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/iishyfishyy/please
    description: A natural language interface for your terminal
    license: MIT
    install: |
      bin.install "please"
    test: |
      system "#{bin}/please", "--version"

# Customize release notes
release:
  github:
    owner: iishyfishyy
    name: please
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install iishyfishyy/tap/please
    ```

    ### Go
    ```bash
    go install github.com/iishyfishyy/please/cmd/please@{{.Version}}
    ```

    ### Install Script
    ```bash
    curl -sSL https://raw.githubusercontent.com/iishyfishyy/please/main/install.sh | bash
    ```

    ### Manual Download
    Download the pre-built binary for your platform below.
